/*
 * Copyright © 2016 TCS and others.  All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 */
package org.opendaylight.cardinal.impl;

//
// Generated by mibgen version 5.1 (03/08/07) when compiling ODL-CARDINAL-MIB in standard metadata mode.
//


// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

/**
 * This interface is used for representing the remote management interface for the "OdlCardinalFeatureUnInstalModule" MBean.
 */
public interface OdlCardinalFeatureUnInstalModuleMBean {

    /**
     * Getter for the "FeatureUnInstalled9" variable.
     */
    public String getFeatureUnInstalled9() throws SnmpStatusException;

    /**
     * Setter for the "FeatureUnInstalled9" variable.
     */
    public void setFeatureUnInstalled9(String x) throws SnmpStatusException;

    /**
     * Checker for the "FeatureUnInstalled9" variable.
     */
    public void checkFeatureUnInstalled9(String x) throws SnmpStatusException;

    /**
     * Getter for the "FeatureUnInstalled8" variable.
     */
    public String getFeatureUnInstalled8() throws SnmpStatusException;

    /**
     * Setter for the "FeatureUnInstalled8" variable.
     */
    public void setFeatureUnInstalled8(String x) throws SnmpStatusException;

    /**
     * Checker for the "FeatureUnInstalled8" variable.
     */
    public void checkFeatureUnInstalled8(String x) throws SnmpStatusException;

    /**
     * Getter for the "FeatureUnInstalled7" variable.
     */
    public String getFeatureUnInstalled7() throws SnmpStatusException;

    /**
     * Setter for the "FeatureUnInstalled7" variable.
     */
    public void setFeatureUnInstalled7(String x) throws SnmpStatusException;

    /**
     * Checker for the "FeatureUnInstalled7" variable.
     */
    public void checkFeatureUnInstalled7(String x) throws SnmpStatusException;

    /**
     * Getter for the "FeatureUnInstalled6" variable.
     */
    public String getFeatureUnInstalled6() throws SnmpStatusException;

    /**
     * Setter for the "FeatureUnInstalled6" variable.
     */
    public void setFeatureUnInstalled6(String x) throws SnmpStatusException;

    /**
     * Checker for the "FeatureUnInstalled6" variable.
     */
    public void checkFeatureUnInstalled6(String x) throws SnmpStatusException;

    /**
     * Getter for the "FeatureUnInstalled5" variable.
     */
    public String getFeatureUnInstalled5() throws SnmpStatusException;

    /**
     * Setter for the "FeatureUnInstalled5" variable.
     */
    public void setFeatureUnInstalled5(String x) throws SnmpStatusException;

    /**
     * Checker for the "FeatureUnInstalled5" variable.
     */
    public void checkFeatureUnInstalled5(String x) throws SnmpStatusException;

    /**
     * Getter for the "FeatureUnInstalled4" variable.
     */
    public String getFeatureUnInstalled4() throws SnmpStatusException;

    /**
     * Setter for the "FeatureUnInstalled4" variable.
     */
    public void setFeatureUnInstalled4(String x) throws SnmpStatusException;

    /**
     * Checker for the "FeatureUnInstalled4" variable.
     */
    public void checkFeatureUnInstalled4(String x) throws SnmpStatusException;

    /**
     * Getter for the "FeatureUnInstalled3" variable.
     */
    public String getFeatureUnInstalled3() throws SnmpStatusException;

    /**
     * Setter for the "FeatureUnInstalled3" variable.
     */
    public void setFeatureUnInstalled3(String x) throws SnmpStatusException;

    /**
     * Checker for the "FeatureUnInstalled3" variable.
     */
    public void checkFeatureUnInstalled3(String x) throws SnmpStatusException;

    /**
     * Getter for the "FeatureUnInstalled2" variable.
     */
    public String getFeatureUnInstalled2() throws SnmpStatusException;

    /**
     * Setter for the "FeatureUnInstalled2" variable.
     */
    public void setFeatureUnInstalled2(String x) throws SnmpStatusException;

    /**
     * Checker for the "FeatureUnInstalled2" variable.
     */
    public void checkFeatureUnInstalled2(String x) throws SnmpStatusException;

    /**
     * Getter for the "FeatureUnInstalled1" variable.
     */
    public String getFeatureUnInstalled1() throws SnmpStatusException;

    /**
     * Setter for the "FeatureUnInstalled1" variable.
     */
    public void setFeatureUnInstalled1(String x) throws SnmpStatusException;

    /**
     * Checker for the "FeatureUnInstalled1" variable.
     */
    public void checkFeatureUnInstalled1(String x) throws SnmpStatusException;

    /**
     * Getter for the "FeatureUnInstalled10" variable.
     */
    public String getFeatureUnInstalled10() throws SnmpStatusException;

    /**
     * Setter for the "FeatureUnInstalled10" variable.
     */
    public void setFeatureUnInstalled10(String x) throws SnmpStatusException;

    /**
     * Checker for the "FeatureUnInstalled10" variable.
     */
    public void checkFeatureUnInstalled10(String x) throws SnmpStatusException;

    /**
     * Getter for the "OdlKarafFeatureListUnInstalled" variable.
     */
    public String getOdlKarafFeatureListUnInstalled() throws SnmpStatusException;

    /**
     * Setter for the "OdlKarafFeatureListUnInstalled" variable.
     */
    public void setOdlKarafFeatureListUnInstalled(String x) throws SnmpStatusException;

    /**
     * Checker for the "OdlKarafFeatureListUnInstalled" variable.
     */
    public void checkOdlKarafFeatureListUnInstalled(String x) throws SnmpStatusException;

}
