/*
 * Copyright © 2016 TCS and others.  All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 */
package org.opendaylight.cardinal.impl;

//
// Generated by mibgen version 5.1 (03/08/07) when compiling ODL-CARDINAL-MIB in standard metadata mode.
//


// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

/**
 * This interface is used for representing the remote management interface for the "OdlCardinalBundleActiveModule" MBean.
 */
public interface OdlCardinalBundleActiveModuleMBean {

    /**
     * Getter for the "Activebundle9" variable.
     */
    public String getActivebundle9() throws SnmpStatusException;

    /**
     * Setter for the "Activebundle9" variable.
     */
    public void setActivebundle9(String x) throws SnmpStatusException;

    /**
     * Checker for the "Activebundle9" variable.
     */
    public void checkActivebundle9(String x) throws SnmpStatusException;

    /**
     * Getter for the "Activebundle8" variable.
     */
    public String getActivebundle8() throws SnmpStatusException;

    /**
     * Setter for the "Activebundle8" variable.
     */
    public void setActivebundle8(String x) throws SnmpStatusException;

    /**
     * Checker for the "Activebundle8" variable.
     */
    public void checkActivebundle8(String x) throws SnmpStatusException;

    /**
     * Getter for the "Activebundle7" variable.
     */
    public String getActivebundle7() throws SnmpStatusException;

    /**
     * Setter for the "Activebundle7" variable.
     */
    public void setActivebundle7(String x) throws SnmpStatusException;

    /**
     * Checker for the "Activebundle7" variable.
     */
    public void checkActivebundle7(String x) throws SnmpStatusException;

    /**
     * Getter for the "Activebundle6" variable.
     */
    public String getActivebundle6() throws SnmpStatusException;

    /**
     * Setter for the "Activebundle6" variable.
     */
    public void setActivebundle6(String x) throws SnmpStatusException;

    /**
     * Checker for the "Activebundle6" variable.
     */
    public void checkActivebundle6(String x) throws SnmpStatusException;

    /**
     * Getter for the "Activebundle5" variable.
     */
    public String getActivebundle5() throws SnmpStatusException;

    /**
     * Setter for the "Activebundle5" variable.
     */
    public void setActivebundle5(String x) throws SnmpStatusException;

    /**
     * Checker for the "Activebundle5" variable.
     */
    public void checkActivebundle5(String x) throws SnmpStatusException;

    /**
     * Getter for the "Activebundle4" variable.
     */
    public String getActivebundle4() throws SnmpStatusException;

    /**
     * Setter for the "Activebundle4" variable.
     */
    public void setActivebundle4(String x) throws SnmpStatusException;

    /**
     * Checker for the "Activebundle4" variable.
     */
    public void checkActivebundle4(String x) throws SnmpStatusException;

    /**
     * Getter for the "Activebundle3" variable.
     */
    public String getActivebundle3() throws SnmpStatusException;

    /**
     * Setter for the "Activebundle3" variable.
     */
    public void setActivebundle3(String x) throws SnmpStatusException;

    /**
     * Checker for the "Activebundle3" variable.
     */
    public void checkActivebundle3(String x) throws SnmpStatusException;

    /**
     * Getter for the "Activebundle2" variable.
     */
    public String getActivebundle2() throws SnmpStatusException;

    /**
     * Setter for the "Activebundle2" variable.
     */
    public void setActivebundle2(String x) throws SnmpStatusException;

    /**
     * Checker for the "Activebundle2" variable.
     */
    public void checkActivebundle2(String x) throws SnmpStatusException;

    /**
     * Getter for the "Activebundle10" variable.
     */
    public String getActivebundle10() throws SnmpStatusException;

    /**
     * Setter for the "Activebundle10" variable.
     */
    public void setActivebundle10(String x) throws SnmpStatusException;

    /**
     * Checker for the "Activebundle10" variable.
     */
    public void checkActivebundle10(String x) throws SnmpStatusException;

    /**
     * Getter for the "Activebundle1" variable.
     */
    public String getActivebundle1() throws SnmpStatusException;

    /**
     * Setter for the "Activebundle1" variable.
     */
    public void setActivebundle1(String x) throws SnmpStatusException;

    /**
     * Checker for the "Activebundle1" variable.
     */
    public void checkActivebundle1(String x) throws SnmpStatusException;

    /**
     * Getter for the "OdKarafBundleListActive" variable.
     */
    public String getOdKarafBundleListActive() throws SnmpStatusException;

    /**
     * Setter for the "OdKarafBundleListActive" variable.
     */
    public void setOdKarafBundleListActive(String x) throws SnmpStatusException;

    /**
     * Checker for the "OdKarafBundleListActive" variable.
     */
    public void checkOdKarafBundleListActive(String x) throws SnmpStatusException;

}
