/*
 * Copyright © 2016 TCS and others.  All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 */
package org.opendaylight.cardinal.impl;
//

// Generated by mibgen version 5.1 (03/08/07) when compiling ODL-CARDINAL-MIB in standard metadata mode.
//

// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

/**
 * This interface is used for representing the remote management interface for
 * the "OdlNetconfEntry" MBean.
 */
public interface OdlNetconfEntryMBean {

    /**
     * Getter for the "OdlNetconfStatus" variable.
     */
    public String getOdlNetconfStatus() throws SnmpStatusException;

    /**
     * Setter for the "OdlNetconfStatus" variable.
     */
    public void setOdlNetconfStatus(String x) throws SnmpStatusException;

    /**
     * Checker for the "OdlNetconfStatus" variable.
     */
    public void checkOdlNetconfStatus(String x) throws SnmpStatusException;

    /**
     * Getter for the "OdlNetconfPort" variable.
     */
    public String getOdlNetconfPort() throws SnmpStatusException;

    /**
     * Setter for the "OdlNetconfPort" variable.
     */
    public void setOdlNetconfPort(String x) throws SnmpStatusException;

    /**
     * Checker for the "OdlNetconfPort" variable.
     */
    public void checkOdlNetconfPort(String x) throws SnmpStatusException;

    /**
     * Getter for the "OdlNetconfHost" variable.
     */
    public String getOdlNetconfHost() throws SnmpStatusException;

    /**
     * Setter for the "OdlNetconfHost" variable.
     */
    public void setOdlNetconfHost(String x) throws SnmpStatusException;

    /**
     * Checker for the "OdlNetconfHost" variable.
     */
    public void checkOdlNetconfHost(String x) throws SnmpStatusException;

    /**
     * Getter for the "OdlNetconfNodeId" variable.
     */
    public Byte[] getOdlNetconfNodeId() throws SnmpStatusException;

    /**
     * Setter for the "OdlNetconfNodeId" variable.
     */
    public void setOdlNetconfNodeId(Byte[] x) throws SnmpStatusException;

    /**
     * Checker for the "OdlNetconfNodeId" variable.
     */
    public void checkOdlNetconfNodeId(Byte[] x) throws SnmpStatusException;

}
