/*
 * Copyright © 2016 TCS and others.  All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 */
package org.opendaylight.cardinal.impl;
//

// Generated by mibgen version 5.1 (03/08/07) when compiling ODL-CARDINAL-MIB in standard metadata mode.
//

// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

/**
 * This interface is used for representing the remote management interface for
 * the "OdlNetconfStats2" MBean.
 */
public interface OdlNetconfStats2MBean {

    /**
     * Getter for the "OdlNetconfStatus2" variable.
     */
    public String getOdlNetconfStatus2() throws SnmpStatusException;

    /**
     * Setter for the "OdlNetconfStatus2" variable.
     */
    public void setOdlNetconfStatus2(String x) throws SnmpStatusException;

    /**
     * Checker for the "OdlNetconfStatus2" variable.
     */
    public void checkOdlNetconfStatus2(String x) throws SnmpStatusException;

    /**
     * Getter for the "OdlNetconfPort2" variable.
     */
    public String getOdlNetconfPort2() throws SnmpStatusException;

    /**
     * Setter for the "OdlNetconfPort2" variable.
     */
    public void setOdlNetconfPort2(String x) throws SnmpStatusException;

    /**
     * Checker for the "OdlNetconfPort2" variable.
     */
    public void checkOdlNetconfPort2(String x) throws SnmpStatusException;

    /**
     * Getter for the "OdlNetconfHost2" variable.
     */
    public String getOdlNetconfHost2() throws SnmpStatusException;

    /**
     * Setter for the "OdlNetconfHost2" variable.
     */
    public void setOdlNetconfHost2(String x) throws SnmpStatusException;

    /**
     * Checker for the "OdlNetconfHost2" variable.
     */
    public void checkOdlNetconfHost2(String x) throws SnmpStatusException;

    /**
     * Getter for the "OdlNetconfNodeId2" variable.
     */
    public String getOdlNetconfNodeId2() throws SnmpStatusException;

    /**
     * Setter for the "OdlNetconfNodeId2" variable.
     */
    public void setOdlNetconfNodeId2(String x) throws SnmpStatusException;

    /**
     * Checker for the "OdlNetconfNodeId2" variable.
     */
    public void checkOdlNetconfNodeId2(String x) throws SnmpStatusException;

}
