/*
 * Copyright © 2016 TCS and others.  All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 */
package org.opendaylight.cardinal.impl;
//

// Generated by mibgen version 5.1 (03/08/07) when compiling ODL-CARDINAL-MIB.
//

// java imports
//
import java.io.Serializable;

// jmx imports
//
import javax.management.MBeanServer;
import com.sun.management.snmp.SnmpString;
import com.sun.management.snmp.SnmpStatusException;

// jdmk imports
//
import com.sun.management.snmp.agent.SnmpMib;

/**
 * The class is used for implementing the "OdlNetconfStats1" group. The group is
 * defined with the following oid: 1.3.6.1.3.1.1.14.
 */
public class OdlNetconfStats1 implements OdlNetconfStats1MBean, Serializable {

    /**
     * Variable for storing the value of "OdlNetconfStatus1". The variable is
     * identified by: "1.3.6.1.3.1.1.14.4".
     */
    protected String OdlNetconfStatus1 = new String("JDMK 5.1");

    /**
     * Variable for storing the value of "OdlNetconfPort1". The variable is
     * identified by: "1.3.6.1.3.1.1.14.3".
     */
    protected String OdlNetconfPort1 = new String("JDMK 5.1");

    /**
     * Variable for storing the value of "OdlNetconfHost1". The variable is
     * identified by: "1.3.6.1.3.1.1.14.2".
     */
    protected String OdlNetconfHost1 = new String("JDMK 5.1");

    /**
     * Variable for storing the value of "OdlNetconfNodeId1". The variable is
     * identified by: "1.3.6.1.3.1.1.14.1".
     */
    protected String OdlNetconfNodeId1 = new String("JDMK 5.1");

    /**
     * Constructor for the "OdlNetconfStats1" group. If the group contains a
     * table, the entries created through an SNMP SET will not be registered in
     * Java DMK.
     */
    public OdlNetconfStats1(SnmpMib myMib) {
    }

    /**
     * Constructor for the "OdlNetconfStats1" group. If the group contains a
     * table, the entries created through an SNMP SET will be AUTOMATICALLY
     * REGISTERED in Java DMK.
     */
    public OdlNetconfStats1(SnmpMib myMib, MBeanServer server) {
    }

    /**
     * Getter for the "OdlNetconfStatus1" variable.
     */
    public String getOdlNetconfStatus1() throws SnmpStatusException {
        return OdlNetconfStatus1;
    }

    /**
     * Setter for the "OdlNetconfStatus1" variable.
     */
    public void setOdlNetconfStatus1(String x) throws SnmpStatusException {
        OdlNetconfStatus1 = x;
    }

    /**
     * Checker for the "OdlNetconfStatus1" variable.
     */
    public void checkOdlNetconfStatus1(String x) throws SnmpStatusException {
        //
        // Add your own checking policy.
        //
    }

    /**
     * Getter for the "OdlNetconfPort1" variable.
     */
    public String getOdlNetconfPort1() throws SnmpStatusException {
        return OdlNetconfPort1;
    }

    /**
     * Setter for the "OdlNetconfPort1" variable.
     */
    public void setOdlNetconfPort1(String x) throws SnmpStatusException {
        OdlNetconfPort1 = x;
    }

    /**
     * Checker for the "OdlNetconfPort1" variable.
     */
    public void checkOdlNetconfPort1(String x) throws SnmpStatusException {
        //
        // Add your own checking policy.
        //
    }

    /**
     * Getter for the "OdlNetconfHost1" variable.
     */
    public String getOdlNetconfHost1() throws SnmpStatusException {
        return OdlNetconfHost1;
    }

    /**
     * Setter for the "OdlNetconfHost1" variable.
     */
    public void setOdlNetconfHost1(String x) throws SnmpStatusException {
        OdlNetconfHost1 = x;
    }

    /**
     * Checker for the "OdlNetconfHost1" variable.
     */
    public void checkOdlNetconfHost1(String x) throws SnmpStatusException {
        //
        // Add your own checking policy.
        //
    }

    /**
     * Getter for the "OdlNetconfNodeId1" variable.
     */
    public String getOdlNetconfNodeId1() throws SnmpStatusException {
        return OdlNetconfNodeId1;
    }

    /**
     * Setter for the "OdlNetconfNodeId1" variable.
     */
    public void setOdlNetconfNodeId1(String x) throws SnmpStatusException {
        OdlNetconfNodeId1 = x;
    }

    /**
     * Checker for the "OdlNetconfNodeId1" variable.
     */
    public void checkOdlNetconfNodeId1(String x) throws SnmpStatusException {
        //
        // Add your own checking policy.
        //
    }

}
