/*
 * Copyright © 2016 TCS and others.  All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 */
package org.opendaylight.cardinal.impl;
//

// Generated by mibgen version 5.1 (03/08/07) when compiling ODL-CARDINAL-MIB.
//

// java imports
//
import java.io.Serializable;

// jmx imports
//
import javax.management.MBeanServer;
import com.sun.management.snmp.SnmpString;
import com.sun.management.snmp.SnmpStatusException;

// jdmk imports
//
import com.sun.management.snmp.agent.SnmpMib;

/**
 * The class is used for implementing the "OdlNetconfTables" group. The group is
 * defined with the following oid: 1.3.6.1.3.1.1.16.
 */
public class OdlNetconfTables implements OdlNetconfTablesMBean, Serializable {

    /**
     * Variable for storing the value of "OdlNetconfTable". The variable is
     * identified by: "1.3.6.1.3.1.1.16.1".
     */
    protected TableOdlNetconfTable OdlNetconfTable;

    /**
     * Constructor for the "OdlNetconfTables" group. If the group contains a
     * table, the entries created through an SNMP SET will not be registered in
     * Java DMK.
     */
    public OdlNetconfTables(SnmpMib myMib) {
        OdlNetconfTable = new TableOdlNetconfTable(myMib);
    }

    /**
     * Constructor for the "OdlNetconfTables" group. If the group contains a
     * table, the entries created through an SNMP SET will be AUTOMATICALLY
     * REGISTERED in Java DMK.
     */
    public OdlNetconfTables(SnmpMib myMib, MBeanServer server) {
        OdlNetconfTable = new TableOdlNetconfTable(myMib, server);
    }

    /**
     * Access the "OdlNetconfTable" variable.
     */
    public TableOdlNetconfTable accessOdlNetconfTable() throws SnmpStatusException {
        return OdlNetconfTable;
    }

    /**
     * Access the "OdlNetconfTable" variable as a bean indexed property.
     */
    public OdlNetconfEntryMBean[] getOdlNetconfTable() throws SnmpStatusException {
        return OdlNetconfTable.getEntries();
    }

}
