/*
 * Copyright © 2016 TCS and others.  All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 */
package org.opendaylight.cardinal.impl;
//

// Generated by mibgen version 5.1 (03/08/07) when compiling ODL-CARDINAL-MIB.
//

// java imports
//
import java.io.Serializable;

// jmx imports
//
import javax.management.MBeanServer;
import com.sun.management.snmp.SnmpString;
import com.sun.management.snmp.SnmpStatusException;

// jdmk imports
//
import com.sun.management.snmp.agent.SnmpMib;

/**
 * The class is used for implementing the "OdlNetconfStats2" group. The group is
 * defined with the following oid: 1.3.6.1.3.1.1.15.
 */
public class OdlNetconfStats2 implements OdlNetconfStats2MBean, Serializable {

    /**
     * Variable for storing the value of "OdlNetconfStatus2". The variable is
     * identified by: "1.3.6.1.3.1.1.15.4".
     */
    protected String OdlNetconfStatus2 = new String("JDMK 5.1");

    /**
     * Variable for storing the value of "OdlNetconfPort2". The variable is
     * identified by: "1.3.6.1.3.1.1.15.3".
     */
    protected String OdlNetconfPort2 = new String("JDMK 5.1");

    /**
     * Variable for storing the value of "OdlNetconfHost2". The variable is
     * identified by: "1.3.6.1.3.1.1.15.2".
     */
    protected String OdlNetconfHost2 = new String("JDMK 5.1");

    /**
     * Variable for storing the value of "OdlNetconfNodeId2". The variable is
     * identified by: "1.3.6.1.3.1.1.15.1".
     */
    protected String OdlNetconfNodeId2 = new String("JDMK 5.1");

    /**
     * Constructor for the "OdlNetconfStats2" group. If the group contains a
     * table, the entries created through an SNMP SET will not be registered in
     * Java DMK.
     */
    public OdlNetconfStats2(SnmpMib myMib) {
    }

    /**
     * Constructor for the "OdlNetconfStats2" group. If the group contains a
     * table, the entries created through an SNMP SET will be AUTOMATICALLY
     * REGISTERED in Java DMK.
     */
    public OdlNetconfStats2(SnmpMib myMib, MBeanServer server) {
    }

    /**
     * Getter for the "OdlNetconfStatus2" variable.
     */
    public String getOdlNetconfStatus2() throws SnmpStatusException {
        return OdlNetconfStatus2;
    }

    /**
     * Setter for the "OdlNetconfStatus2" variable.
     */
    public void setOdlNetconfStatus2(String x) throws SnmpStatusException {
        OdlNetconfStatus2 = x;
    }

    /**
     * Checker for the "OdlNetconfStatus2" variable.
     */
    public void checkOdlNetconfStatus2(String x) throws SnmpStatusException {
        //
        // Add your own checking policy.
        //
    }

    /**
     * Getter for the "OdlNetconfPort2" variable.
     */
    public String getOdlNetconfPort2() throws SnmpStatusException {
        return OdlNetconfPort2;
    }

    /**
     * Setter for the "OdlNetconfPort2" variable.
     */
    public void setOdlNetconfPort2(String x) throws SnmpStatusException {
        OdlNetconfPort2 = x;
    }

    /**
     * Checker for the "OdlNetconfPort2" variable.
     */
    public void checkOdlNetconfPort2(String x) throws SnmpStatusException {
        //
        // Add your own checking policy.
        //
    }

    /**
     * Getter for the "OdlNetconfHost2" variable.
     */
    public String getOdlNetconfHost2() throws SnmpStatusException {
        return OdlNetconfHost2;
    }

    /**
     * Setter for the "OdlNetconfHost2" variable.
     */
    public void setOdlNetconfHost2(String x) throws SnmpStatusException {
        OdlNetconfHost2 = x;
    }

    /**
     * Checker for the "OdlNetconfHost2" variable.
     */
    public void checkOdlNetconfHost2(String x) throws SnmpStatusException {
        //
        // Add your own checking policy.
        //
    }

    /**
     * Getter for the "OdlNetconfNodeId2" variable.
     */
    public String getOdlNetconfNodeId2() throws SnmpStatusException {
        return OdlNetconfNodeId2;
    }

    /**
     * Setter for the "OdlNetconfNodeId2" variable.
     */
    public void setOdlNetconfNodeId2(String x) throws SnmpStatusException {
        OdlNetconfNodeId2 = x;
    }

    /**
     * Checker for the "OdlNetconfNodeId2" variable.
     */
    public void checkOdlNetconfNodeId2(String x) throws SnmpStatusException {
        //
        // Add your own checking policy.
        //
    }

}
