/*
 * Copyright © 2016 TCS and others.  All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 */
package org.opendaylight.cardinal.impl;
//

// Generated by mibgen version 5.1 (03/08/07) when compiling ODL-CARDINAL-MIB.
//

// java imports
//
import java.io.Serializable;

// jmx imports
//
import javax.management.MBeanServer;
import com.sun.management.snmp.SnmpString;
import com.sun.management.snmp.SnmpStatusException;

// jdmk imports
//
import com.sun.management.snmp.agent.SnmpMib;

/**
 * The class is used for implementing the "OdlOpenflowTables" group. The group
 * is defined with the following oid: 1.3.6.1.3.1.1.13.
 */
public class OdlOpenflowTables implements OdlOpenflowTablesMBean, Serializable {

    /**
     * Variable for storing the value of "NetOpenflowTable". The variable is
     * identified by: "1.3.6.1.3.1.1.13.1".
     */
    protected TableNetOpenflowTable NetOpenflowTable;

    /**
     * Constructor for the "OdlOpenflowTables" group. If the group contains a
     * table, the entries created through an SNMP SET will not be registered in
     * Java DMK.
     */
    public OdlOpenflowTables(SnmpMib myMib) {
        NetOpenflowTable = new TableNetOpenflowTable(myMib);
    }

    /**
     * Constructor for the "OdlOpenflowTables" group. If the group contains a
     * table, the entries created through an SNMP SET will be AUTOMATICALLY
     * REGISTERED in Java DMK.
     */
    public OdlOpenflowTables(SnmpMib myMib, MBeanServer server) {
        NetOpenflowTable = new TableNetOpenflowTable(myMib, server);
    }

    /**
     * Access the "NetOpenflowTable" variable.
     */
    public TableNetOpenflowTable accessNetOpenflowTable() throws SnmpStatusException {
        return NetOpenflowTable;
    }

    /**
     * Access the "NetOpenflowTable" variable as a bean indexed property.
     */
    public NetOpenflowEntryMBean[] getNetOpenflowTable() throws SnmpStatusException {
        return NetOpenflowTable.getEntries();
    }

}
